### ISSUE TITLE
description: "An electron-vue project"

### ISSUE THREAD

**Issue by probonopd** [NightFarmer/apk-parser#1]
https://github.com/NightFarmer/apk-parser/blob/faec4cddfb804091dad40a3c485f6e7b113d4135/package.json#L5

The description: "An electron-vue project" does not tell what this application does. Please use a more useful description.

Reference:
https://github.com/AppImage/appimage.github.io/pull/660

**Comment by NightFarmer** [comment]
I modified it in the latest commit
😁
