### ISSUE TITLE
Please provide English UI

### ISSUE THREAD

**Issue by probonopd** [NightFarmer/apk-parser#2]
Please provide English UI.

Right now it looks broken on an English system with no Chinese fonts installed:

请提供英文界面。

现在在一个没有安装中文字体的英文系统上看起来很糟糕：

![](https://github.com/AppImage/appimage.github.io/raw/1f0d7cf4637fbfc493ef20138b344bc7c39289b1/database/apk-parser/screenshot.png)

Reference:
https://github.com/AppImage/appimage.github.io/pull/660

**Comment by NightFarmer** [comment]
thanks for your issue 
I added the English UI in version 1.1.0. In the case of non-Chinese environments, it uses the English UI instead of the Chinese UI.
