### ISSUE TITLE
下载地址已失效

### ISSUE THREAD

**Issue by VencentYChen** [NightFarmer/apk-parser#3]
v1.0.0及v1.1.0下载地址都提示404，请提供新的下载地址

**Comment by NightFarmer** [comment]
我这里好像是可以正常下载的  
不过我给v1.1.0版本增加了备用下载地址  
[Mac DownLoad](http://orh51lve9.bkt.clouddn.com/apk-parser-1.1.0.dmg)
[Linux DownLoad](http://orh51lve9.bkt.clouddn.com/apk-parser-1.1.0-x86_64.AppImage)
[Windows DownLoad](http://orh51lve9.bkt.clouddn.com/apk-parser%20Setup%201.1.0.exe)
你可以试一下
